"""Run once: python add_words.py — inserts new vocab without duplicating existing cards."""
import sqlite3, os

DB_PATH = os.path.join(os.path.dirname(__file__), "kanji.db")

NEW_WORDS = [
    # 招 group
    ("招", "しょう / まねく", "to invite, to call over", None, None, None),
    ("招く", "まねく", "to invite / to call someone", None, None, None),
    ("招待", "しょうたい", "invitation", None, None, None),
    ("招集", "しょうしゅう", "convening / calling together", None, None, None),
    ("招致", "しょうち", "inviting (e.g. events, countries)", None, None, None),
    # 給 group
    ("給", "きゅう", "to supply, to provide, to give (money, food, or resources)", None, None, None),
    ("給料", "きゅうりょう", "salary", None, None, None),
    ("支給", "しきゅう", "payment / provision of money", None, None, None),
    ("給与", "きゅうよ", "wages / salary (formal)", None, None, None),
    ("給食", "きゅうしょく", "school lunch (food provided)", None, None, None),
    ("給水", "きゅうすい", "water supply", None, None, None),
    ("供給", "きょうきゅう", "supply (goods, electricity, etc.)", None, None, None),
    # 人間関係 group
    ("人間", "にんげん", "human / people", None, None, None),
    ("関係", "かんけい", "relation / connection", None, None, None),
    ("友人関係", "ゆうじんかんけい", "friendship relations", None, None, None),
    ("家族関係", "かぞくかんけい", "family relationships", None, None, None),
    ("社会関係", "しゃかいかんけい", "social relations", None, None, None),
    ("親", "おや", "parent(s)", None, None, None),
    ("親友", "しんゆう", "close friend", None, None, None),
    ("親切", "しんせつ", "kindness / kind", None, None, None),
    ("親戚", "しんせき", "relatives", None, None, None),
    ("親しい", "したしい", "close (in relationship), familiar, friendly / intimate", None, None, None),
    ("続く", "つづく", "to continue — intransitive (something continues by itself)", None, None, None),
    ("続ける", "つづける", "to continue doing something — transitive (you do it actively)", None, None, None),
    ("手続き", "てつづき", "procedure, formal process, administrative steps", None, None, None),
    # Travel
    ("飛行機", "ひこうき", "airplane", None, None, None),
    ("空港", "くうこう", "airport", None, None, None),
    ("航空", "こうくう", "air travel / air transport (e.g. 日本航空 = JAL)", None, None, None),
    ("出発", "しゅっぱつ", "departure", None, None, None),
    ("到着", "とうちゃく", "arrival", None, None, None),
    # Change
    ("変更", "へんこう", "change, modification, alteration (e.g. パスワードを変更する)", None, None, None),
    ("変化", "へんか", "change / transformation — natural or over time (e.g. 天気の変化)", None, None, None),
    ("変わる", "かわる", "to change by itself (intransitive)", None, None, None),
    ("変える", "かえる", "to change something actively (transitive)", None, None, None),
    # 利用 group
    ("利用", "りよう", "use, utilization, making use of something for a purpose", None, None, None),
    ("利用者", "りようしゃ", "user", None, None, None),
    ("利用料", "りようりょう", "usage fee", None, None, None),
    ("便利", "べんり", "convenient, useful, handy / easy to use", None, None, None),
    ("不便", "ふべん", "inconvenient", None, None, None),
    ("便益", "べんえき", "benefit", None, None, None),
    # Forget / Help / Cooperation
    ("忘れる", "わすれる", "to forget", None, None, None),
    ("忘年会", "ぼうねんかい", "year-end party", None, None, None),
    ("助ける", "たすける", "to help / to rescue", None, None, None),
    ("助手", "じょしゅ", "assistant", None, None, None),
    ("体力", "たいりょく", "physical strength, stamina", None, None, None),
    ("協力", "きょうりょく", "cooperation, collaboration", None, None, None),
    ("担当", "たんとう", "being in charge", None, None, None),
    ("担当者", "たんとうしゃ", "person in charge", None, None, None),
    ("報告", "ほうこく", "report (します verb)", None, None, None),
    ("連休", "れんきゅう", "consecutive holidays", None, None, None),
    ("連絡", "れんらく", "contact / communication (します verb)", None, None, None),
    ("相談", "そうだん", "consultation, to discuss / seek advice (します verb)", None, None, None),
    ("募集", "ぼしゅう", "recruitment (します verb)", None, None, None),
    ("集まる", "あつまる", "to gather (intransitive — by itself)", None, None, None),
    ("集める", "あつめる", "to collect (transitive)", None, None, None),
    ("輸出", "ゆしゅつ", "export", None, None, None),
    ("輸入", "ゆにゅう", "import", None, None, None),
    ("表現", "ひょうげん", "expression / to express (words, feelings, ideas)", None, None, None),
    ("文", "ぶん", "sentence, text / writing", None, None, None),
    ("文型", "ぶんけい", "sentence structure pattern", None, None, None),
    ("文法", "ぶんぽう", "grammar, rules of a language", None, None, None),
    ("例", "れい", "example", None, None, None),
    ("練習", "れんしゅう", "practice / training / exercise", None, None, None),
    # Answer / Mail
    ("答え", "こたえ", "answer (答えを出す = to give an answer)", None, None, None),
    ("航空便", "こうくうびん", "air mail / air shipment", None, None, None),
    # Movement
    ("送ります", "おくります", "to send / to take someone (to a place) / to see off", None, None, None),
    ("散歩します", "さんぽします", "to take a walk", None, None, None),
    ("歩く", "あるく", "to walk", None, None, None),
    ("走る", "はしる", "to run", None, None, None),
    ("泳ぐ", "およぐ", "to swim", None, None, None),
    ("起きます", "おきます", "to wake up", None, None, None),
    ("寝ます", "ねます", "to sleep", None, None, None),
    ("住みます", "すみます", "to live (in a place)", None, None, None),
    ("生きる", "いきる", "to live (to be alive)", None, None, None),
    ("人生", "じんせい", "human life", None, None, None),
    ("生活", "せいかつ", "life / living (daily life)", None, None, None),
    ("学生", "がくせい", "student", None, None, None),
    ("生", "なま", "raw / not cooked or processed", None, None, None),
    ("命", "いのち", "life (life force)", None, None, None),
    # Schedule
    ("予定", "よてい", "plan, schedule", None, None, None),
    ("予約します", "よやくします", "to make a reservation / to book", None, None, None),
    ("予約", "よやく", "reservation / booking", None, None, None),
    # Year / Month end
    ("年末", "ねんまつ", "end of the year", None, None, None),
    ("週末", "しゅうまつ", "weekend (Saturday & Sunday)", None, None, None),
    ("末日", "まつじつ", "last day of the month / period", None, None, None),
    ("末っ子", "すえっこ", "youngest child", None, None, None),
    ("末期", "まっき", "final stage / terminal stage", None, None, None),
    # 成 group
    ("成る", "なる", "to become", None, None, None),
    ("成長", "せいちょう", "growth", None, None, None),
    ("成功", "せいこう", "success", None, None, None),
    # 良い / 悪い
    ("良い", "よい", "good (e.g. 良い天気 = good weather)", None, None, None),
    ("悪い", "わるい", "bad", None, None, None),
    # 歴史 group
    ("歴史", "れきし", "history", None, None, None),
    ("世界史", "せかいし", "world history", None, None, None),
    ("日本史", "にほんし", "Japanese history", None, None, None),
    ("史料", "しりょう", "historical documents", None, None, None),
    ("史上", "しじょう", "in history / ever recorded (e.g. 史上最高 = the best ever)", None, None, None),
    # School
    ("授業", "じゅぎょう", "class, lecture", None, None, None),
    # Passive forms
    ("盗まれた", "ぬすまれた", "was stolen (passive form)", None, None, None),
    ("渡された", "わたされた", "was handed / given (passive form)", None, None, None),
    ("呼ばれた", "よばれた", "was called / invited (passive form)", None, None, None),
    ("押された", "おされた", "was pushed / pressed (passive form)", None, None, None),
    # Production / Social
    ("生産します", "せいさんします", "to produce / manufacture", None, None, None),
    ("人口", "じんこう", "population", None, None, None),
    ("込む", "こむ", "to be crowded", None, None, None),
    ("汚い", "きたない", "dirty", None, None, None),
    ("汚れます", "よごれます", "to become dirty", None, None, None),
    ("冷えます", "ひえます", "to become cold", None, None, None),
    ("規則", "きそく", "rules / regulations", None, None, None),
    ("止みます", "やみます", "to stop — used for rain, snow", None, None, None),
    # Adjectives / misc
    ("柔らかい", "やわらかい", "soft", None, None, None),
    ("蒸し暑い", "むしあつい", "hot and humid", None, None, None),
    ("沸かします", "わかします", "to boil (transitive)", None, None, None),
    ("濡れる", "ぬれる", "to get wet", None, None, None),
    ("笑われます", "わらわれます", "to be laughed at (passive)", None, None, None),
    ("懐かしい", "なつかしい", "nostalgic / fondly remembered", None, None, None),
    ("死ぬ", "しぬ", "to die", None, None, None),
    ("怒ります", "おこります", "to get angry", None, None, None),
    ("見学します", "けんがくします", "to observe / go on a field trip", None, None, None),
    ("工場", "こうじょう", "factory", None, None, None),
    ("工事", "こうじ", "construction work", None, None, None),
    ("寝坊します", "ねぼうします", "to oversleep", None, None, None),
    ("留守", "るす", "absence / not at home", None, None, None),
    ("苦い", "にがい", "bitter", None, None, None),
    ("似ています", "にています", "resembles / looks like", None, None, None),
    ("落とします", "おとします", "to drop", None, None, None),
    ("割ります", "わります", "to break / divide", None, None, None),
    ("怒られます", "おこられます", "to be scolded (passive)", None, None, None),
    ("遅刻します", "ちこくします", "to be late", None, None, None),
    ("お大事に", "おだいじに", "take care / get well soon", None, None, None),
    ("残ります", "のこります", "to remain", None, None, None),
    ("決まります", "きまります", "to be decided", None, None, None),
    ("向かい", "むかい", "opposite / across from", None, None, None),
    ("放送", "ほうそう", "broadcast", None, None, None),
    ("進む", "すすむ", "to advance / to proceed", None, None, None),
    ("太陽", "たいよう", "sun", None, None, None),
    ("贈り物", "おくりもの", "gift", None, None, None),
    # Misc objects
    ("氷", "こおり", "ice", None, None, None),
    ("支度", "したく", "preparation", None, None, None),
    ("上手く", "うまく", "well / skillfully", None, None, None),
    ("丈夫", "じょうぶ", "strong / durable / sturdy", None, None, None),
    ("お礼", "おれい", "thanks / gratitude / a thank-you expression", None, None, None),
    ("似合います", "にあいます", "to suit / to look good on", None, None, None),
    ("是非", "ぜひ", "by all means / please (emphatic)", None, None, None),
    ("空いています", "すいています", "not crowded / has space", None, None, None),
    ("品物", "しなもの", "goods / items", None, None, None),
    ("温い", "ぬるい", "lukewarm", None, None, None),
    ("教わります", "おそわります", "to be taught / to learn from someone", None, None, None),
    ("拾います", "ひろいます", "to pick up", None, None, None),
    ("渡します", "わたします", "to hand over / to pass to someone", None, None, None),
    ("改札口", "かいさつぐち", "ticket gate", None, None, None),
    # Emotions
    ("苦しむ", "くるしむ", "to suffer / to be in pain", None, None, None),
    ("悩む", "なやむ", "to worry / to be troubled", None, None, None),
    ("楽しむ", "たのしむ", "to enjoy", None, None, None),
    ("悲しい", "かなしい", "sad", None, None, None),
    ("嬉しい", "うれしい", "happy / glad", None, None, None),
    ("寂しい", "さびしい", "lonely", None, None, None),
    ("眠れない", "ねむれない", "cannot sleep", None, None, None),
    ("眠い", "ねむい", "sleepy", None, None, None),
    ("引きこもり", "ひきこもり", "social withdrawal / shut-in", None, None, None),
    ("お一人様", "おひとりさま", "one person / solo customer", None, None, None),
    ("気分転換", "きぶんてんかん", "change of mood / refreshing oneself", None, None, None),
    ("人間関係が上手", "にんげんかんけいがじょうず", "good at interpersonal relationships", None, None, None),
    ("人間関係が悪い", "にんげんかんけいがわるい", "bad interpersonal relationships", None, None, None),
    ("苦しい", "くるしい", "painful / tough / suffering", None, None, None),
    ("金銭", "きんせん", "money / financial matters", None, None, None),
    ("用", "よう", "use / purpose / for (depends on context)", None, None, None),
    # Childhood / misc
    ("牛乳", "ぎゅうにゅう", "milk (cow's milk)", None, None, None),
    ("全然", "ぜんぜん", "not at all (with negative) / totally (informal positive)", None, None, None),
    ("背", "せ / せい", "back / height (stature)", None, None, None),
    ("初めて", "はじめて", "for the first time / first experience", None, None, None),
    ("美味しさ", "おいしさ", "deliciousness / taste / flavor", None, None, None),
    ("具合", "ぐあい", "condition / state (of health, machine, situation)", None, None, None),
    ("下りる", "おりる", "to go down / descend (stairs, slopes)", None, None, None),
    ("上る", "のぼる", "to go up / climb", None, None, None),
    ("竹", "たけ", "bamboo", None, None, None),
    ("毛", "け", "hair (body), fur (animal), feather", None, None, None),
    ("許り", "ばかり", "only / just / nothing but (slightly negative nuance)", None, None, None),
    ("着きます", "つきます", "to arrive", None, None, None),
    # School / homework
    ("宿題", "しゅくだい", "homework", None, None, None),
    ("一緒", "いっしょ", "together", None, None, None),
    ("空く", "すく", "to become empty / less crowded (e.g. train, restaurant)", None, None, None),
    ("返します", "かえします", "to return / give back", None, None, None),
    ("開きます", "ひらきます", "to open something / for an event to begin", None, None, None),
    ("起こします", "おこします", "to wake someone up / to cause (something to happen)", None, None, None),
    ("遊びます", "あそびます", "to play / to hang out / to enjoy oneself", None, None, None),
    ("流行ります", "はやります", "to become popular / to be in fashion", None, None, None),
    ("出来上がります", "できあがります", "to be completed / finished / ready", None, None, None),
    ("賑やか", "にぎやか", "lively, busy, bustling", None, None, None),
    ("今日中", "きょうじゅう", "by the end of today", None, None, None),
    ("荷物", "にもつ", "luggage / package", None, None, None),
    ("疲れます", "つかれます", "to get tired", None, None, None),
    # Common verbs
    ("頑張ります", "がんばります", "to do one's best / to keep going", None, None, None),
    ("考えます", "かんがえます", "to think / to consider", None, None, None),
    ("喧嘩します", "けんかします", "to fight / quarrel", None, None, None),
    ("彼女", "かのじょ", "she / girlfriend", None, None, None),
    ("顔", "かお", "face", None, None, None),
    ("静か", "しずか", "quiet / calm / peaceful", None, None, None),
    ("言葉", "ことば", "word / language / speech", None, None, None),
    ("西瓜", "すいか", "watermelon", None, None, None),
    # Objects / places
    ("机の上", "つくえのうえ", "on the desk", None, None, None),
    ("置く", "おく", "to put / place", None, None, None),
    ("借ります", "かります", "to borrow", None, None, None),
    ("泊まる", "とまる", "to stay overnight", None, None, None),
    ("湖", "みずうみ", "lake", None, None, None),
    ("窓", "まど", "window", None, None, None),
    ("涼しい", "すずしい", "cool (weather)", None, None, None),
    ("風", "かぜ", "wind / cold (illness)", None, None, None),
    ("景色", "けしき", "scenery / view", None, None, None),
    ("美しい", "うつくしい", "beautiful", None, None, None),
    ("星", "ほし", "star", None, None, None),
    # Classroom
    ("教室", "きょうしつ", "classroom", None, None, None),
    ("水泳", "すいえい", "swimming", None, None, None),
    ("注意", "ちゅうい", "caution / attention / warning", None, None, None),
    ("始めます", "はじめます", "to start something (transitive)", None, None, None),
    ("始まります", "はじまります", "something starts (intransitive)", None, None, None),
    ("大変", "たいへん", "difficult / serious / very", None, None, None),
    ("特に", "とくに", "especially", None, None, None),
    ("覚える", "おぼえる", "to remember / to memorize", None, None, None),
    ("通学", "つうがく", "commuting to school / going to school", None, None, None),
    ("夕飯", "ゆうはん", "dinner", None, None, None),
    ("疲れる", "つかれる", "to get tired", None, None, None),
    # Nature
    ("石", "いし", "stone", None, None, None),
    ("枝", "えだ", "tree branch", None, None, None),
    ("草", "くさ", "grass, weed, plants", None, None, None),
    ("砂", "すな", "sand", None, None, None),
    ("港", "みなと", "harbor", None, None, None),
    # Money / danger / transport
    ("お釣り", "おつり", "change (money returned)", None, None, None),
    ("危険", "きけん", "danger / dangerous", None, None, None),
    ("機械", "きかい", "machine", None, None, None),
    ("結構", "けっこう", "enough / quite / no thank you", None, None, None),
    ("騒ぐ", "さわぐ", "to make noise / to act rowdy", None, None, None),
    ("座る", "すわる", "to sit", None, None, None),
    ("寝坊", "ねぼう", "oversleeping", None, None, None),
    ("捨てる", "すてる", "to throw away / to discard", None, None, None),
    ("苦手", "にがて", "weakness / something you're not good at", None, None, None),
    ("反対", "はんたい", "opposition / disagree / opposite", None, None, None),
    ("賛成", "さんせい", "agreement / agree", None, None, None),
    ("意見", "いけん", "opinion / idea", None, None, None),
    ("お辞儀", "おじぎ", "bow / showing respect", None, None, None),
    ("機会", "きかい", "opportunity / chance", None, None, None),
    ("お知らせ", "おしらせ", "notice / announcement / information", None, None, None),
    ("娘", "むすめ", "daughter", None, None, None),
    ("息子", "むすこ", "son", None, None, None),
    ("なかなか", "なかなか", "quite / pretty (positive) / not easily (negative)", None, None, None),
    ("時々", "ときどき", "sometimes / occasionally (時々)", None, None, None),
    ("都合", "つごう", "situation / circumstances / convenience", None, None, None),
    ("時", "とき", "time / when (時)", None, None, None),
    ("の間", "のあいだ", "during / while / period of time", None, None, None),
    ("席", "せき", "seat / place to sit", None, None, None),
    ("文章", "ぶんしょう", "a group of sentences / written text / passage", None, None, None),
    # Final
    ("次", "つぎ", "next / the following / the one after this", None, None, None),
    ("辞書", "じしょ", "dictionary", None, None, None),
    ("帽子", "ぼうし", "hat / cap", None, None, None),
    ("温かい", "あたたかい", "warm", None, None, None),
    ("見学", "けんがく", "visiting / observing / touring (to learn)", None, None, None),
    ("数", "すう", "number / quantity", None, None, None),
    ("数える", "かぞえる", "to count", None, None, None),
    ("嫌い", "きらい", "dislike / don't like", None, None, None),
    ("乗り換え", "のりかえ", "transfer / changing from one vehicle to another", None, None, None),
    ("お菓子", "おかし", "sweets / snacks", None, None, None),
    ("食事会", "しょくじかい", "dinner party / meal gathering", None, None, None),
    ("音楽会", "おんがくかい", "concert / music event / music recital", None, None, None),
    # New batch
    ("試合", "しあい", "match / game / competition", None, None, None),
    ("意味", "いみ", "meaning / sense", None, None, None),
    ("押します", "おします", "to push / to press", None, None, None),
    ("教える", "おしえる", "to teach / to tell", None, None, None),
    ("教育", "きょういく", "education", None, None, None),
    ("教科", "きょうか", "school subject", None, None, None),
    ("教科書", "きょうかしょ", "textbook", None, None, None),
    ("教師", "きょうし", "teacher", None, None, None),
    ("教授", "きょうじゅ", "professor", None, None, None),
    ("教会", "きょうかい", "church", None, None, None),
    ("仏教", "ぶっきょう", "Buddhism", None, None, None),
    ("キリスト教", "きりすときょう", "Christianity", None, None, None),
    ("教育する", "きょういくする", "to educate", None, None, None),
    ("教習", "きょうしゅう", "training (driving, skills, etc.)", None, None, None),
    ("教材", "きょうざい", "teaching material", None, None, None),
    ("向こう", "むこう", "over there / the other side / beyond", None, None, None),
    ("混みます", "こみます", "to become crowded / to be crowded", None, None, None),
    ("止めます", "やめます", "to stop / quit / give up (something you are doing)", None, None, None),
    ("書類", "しょるい", "documents / papers", None, None, None),
    ("図書", "としょ", "books / library materials", None, None, None),
    ("図書館", "としょかん", "library", None, None, None),
    ("書店", "しょてん", "bookstore", None, None, None),
    ("申込書", "もうしこみしょ", "application form", None, None, None),
    ("報告書", "ほうこくしょ", "report", None, None, None),
    ("契約書", "けいやくしょ", "contract", None, None, None),
    ("説明書", "せつめいしょ", "instruction manual", None, None, None),
    ("証明書", "しょうめいしょ", "certificate", None, None, None),
    ("温度", "おんど", "temperature", None, None, None),
    ("題名", "だいめい", "title (of a book, movie, etc.)", None, None, None),
    ("問題", "もんだい", "problem / question", None, None, None),
    ("課題", "かだい", "assignment / task", None, None, None),
    ("笑います", "わらいます", "to laugh / to smile", None, None, None),
    ("遅れます", "おくれます", "to be late (for time/schedule)", None, None, None),
    ("遅刻", "ちこく", "being late (for class/work)", None, None, None),
    ("遅い", "おそい", "late (time is late / slow)", None, None, None),
    ("変化します", "へんかします", "to change / to transform / to vary", None, None, None),
    ("下ります", "おります", "to go down (from a high place, mountain, stairs)", None, None, None),
    ("降ります", "おります", "to get off (train, bus, taxi) / to come down (rain, snow)", None, None, None),
    ("登ります", "のぼります", "to climb / to go up (mountain, hill, tree, stairs)", None, None, None),
    ("速い", "はやい", "fast / speedy (used for speed: running, cars, internet)", None, None, None),
    ("早い", "はやい", "early / soon (used for time: morning, arrival)", None, None, None),
    ("盗みます", "ぬすみます", "to steal", None, None, None),
    ("沸きます", "わきます", "water boils", None, None, None),
    ("遠い", "とおい", "far / distant", None, None, None),
    ("遠く", "とおく", "far away", None, None, None),
    ("近い", "ちかい", "near", None, None, None),
    ("増える", "ふえる", "to increase (intransitive)", None, None, None),
    ("減る", "へる", "to decrease (intransitive)", None, None, None),
    ("増やす", "ふやす", "to increase something (transitive)", None, None, None),
    ("減らす", "へらす", "to decrease something (transitive)", None, None, None),
    ("増やします", "ふやします", "to increase something (transitive, polite)", None, None, None),
    ("減らします", "へらします", "to decrease something (transitive, polite)", None, None, None),
    ("増えます", "ふえます", "something increases (intransitive, polite)", None, None, None),
    ("減ります", "へります", "something decreases (intransitive, polite)", None, None, None),
    ("上げます", "あげます", "to raise / increase something", None, None, None),
    ("下げます", "さげます", "to lower / reduce something", None, None, None),
    ("上がります", "あがります", "something rises / goes up", None, None, None),
    ("下がります", "さがります", "something falls / goes down", None, None, None),
    # Counters
    ("3つ", "みっつ (General objects)", "three things", None, None, None),
    ("2人", "ふたり (People)", "two people", None, None, None),
    ("1本", "いっぽん (Long objects)", "one bottle", None, None, None),
    ("5枚", "ごまい (Flat objects)", "five sheets", None, None, None),
    ("6個", "ろっこ (Small objects)", "six items", None, None, None),
    ("2回", "にかい (Times/occurrences)", "two times", None, None, None),
    ("5分", "ごふん (Minutes)", "five minutes", None, None, None),
    ("8時", "はちじ (Hours/o'clock)", "eight o'clock", None, None, None),
    ("3日", "みっか (Days)", "three days", None, None, None),
    ("10年", "じゅうねん (Years)", "ten years", None, None, None),
    ("6ヶ月", "ろっかげつ (Months)", "six months", None, None, None),
    ("2週間", "にしゅうかん (Weeks)", "two weeks", None, None, None),
    ("30秒", "さんじゅうびょう (Seconds)", "thirty seconds", None, None, None),
    ("20歳", "はたち / にじゅっさい (Age)", "twenty years old", None, None, None),
    ("5階", "ごかい (Floors)", "fifth floor", None, None, None),
    ("2台", "にだい (Machines/vehicles)", "two cars", None, None, None),
    ("4冊", "よんさつ (Books/notebooks)", "four books", None, None, None),
    ("1匹", "いっぴき (Small animals)", "one cat", None, None, None),
    ("3羽", "さんわ (Birds/rabbits)", "three birds", None, None, None),
    ("3杯", "さんばい (Cups/glasses)", "three cups", None, None, None),
    ("2着", "にちゃく (Clothes)", "two shirts", None, None, None),
    ("1足", "いっそく (Pairs of shoes/socks)", "one pair", None, None, None),
    ("2通", "につう (Letters/documents)", "two letters", None, None, None),
    ("5件", "ごけん (Cases/matters)", "five cases", None, None, None),
    ("3点", "さんてん (Points/items)", "three items", None, None, None),
    ("2組", "にくみ (Groups/sets)", "two groups", None, None, None),
    ("3列", "さんれつ (Rows/lines)", "three rows", None, None, None),
    ("4行", "よんぎょう (Lines of text)", "four lines", None, None, None),
    ("2箱", "にはこ (Boxes)", "two boxes", None, None, None),
    ("1袋", "ひとふくろ (Bags/packages)", "one bag", None, None, None),
    ("4缶", "よんかん (Cans)", "four cans", None, None, None),
    ("3名", "さんめい (Polite people)", "three people", None, None, None),
    ("2校", "にこう (Schools)", "two schools", None, None, None),
    ("3社", "さんしゃ (Companies/shrines)", "three companies", None, None, None),
    ("5駅", "ごえき (Stations)", "five stations", None, None, None),
    ("2票", "にひょう (Votes/tickets)", "two votes", None, None, None),
    ("1面", "いちめん (Faces/screens)", "one screen", None, None, None),
    ("3粒", "さんつぶ (Small round objects)", "three grains", None, None, None),
    ("1滴", "いってき (Drops of liquid)", "one drop", None, None, None),
    ("2曲", "にきょく (Songs/music)", "two songs", None, None, None),
    ("1発", "いっぱつ (Shots/messages/flights)", "one shot", None, None, None),
    ("2膳", "にぜん (Chopstick sets/bowls)", "two sets", None, None, None),
    ("4軒", "よんけん (Houses/buildings)", "four houses", None, None, None),
    ("10戸", "じゅっこ (Households)", "ten households", None, None, None),
    ("1丁", "いっちょう (Guns/tofu/streets)", "one item", None, None, None),
    ("1隻", "いっせき (Ships/boats)", "one ship", None, None, None),
    ("2艘", "にそう (Small boats)", "two boats", None, None, None),
    ("2頭の牛", "にとう の うし (Large animals)", "two cows", None, None, None),
    # Time expressions
    ("今日", "きょう", "today", None, None, None),
    ("明日", "あした / あす", "tomorrow", None, None, None),
    ("昨日", "きのう", "yesterday", None, None, None),
    ("一昨日", "おととい", "the day before yesterday", None, None, None),
    ("一昨昨日", "さきおととい", "three days ago", None, None, None),
    ("明後日", "あさって", "the day after tomorrow", None, None, None),
    ("明明後日", "しあさって", "in three days", None, None, None),
    ("毎日", "まいにち", "every day", None, None, None),
    ("今朝", "けさ", "this morning", None, None, None),
    ("今晩", "こんばん", "tonight", None, None, None),
    ("今夜", "こんや", "tonight", None, None, None),
    ("昨夜", "ゆうべ / さくや", "last night", None, None, None),
    ("明晩", "みょうばん", "tomorrow night", None, None, None),
    ("先週", "せんしゅう", "last week", None, None, None),
    ("今週", "こんしゅう", "this week", None, None, None),
    ("来週", "らいしゅう", "next week", None, None, None),
    ("先月", "せんげつ", "last month", None, None, None),
    ("今月", "こんげつ", "this month", None, None, None),
    ("来月", "らいげつ", "next month", None, None, None),
    ("去年", "きょねん", "last year", None, None, None),
    ("今年", "ことし", "this year", None, None, None),
    ("来年", "らいねん", "next year", None, None, None),
]


def main():
    if not os.path.exists(DB_PATH):
        print(f"Database not found at {DB_PATH}. Start app.py first to create it.")
        return

    conn = sqlite3.connect(DB_PATH)
    existing = {row[0] for row in conn.execute("SELECT kanji FROM cards")}

    added = 0
    skipped = 0
    for word in NEW_WORDS:
        kanji = word[0]
        if kanji in existing:
            skipped += 1
        else:
            conn.execute(
                "INSERT INTO cards (kanji, reading, meaning, example_word, example_reading, example_meaning) VALUES (?,?,?,?,?,?)",
                word,
            )
            existing.add(kanji)
            added += 1

    conn.commit()

    conn2 = sqlite3.connect(DB_PATH)
    recent = conn2.execute("SELECT kanji, reading, meaning FROM cards ORDER BY id DESC LIMIT 10").fetchall()
    conn2.close()

    print(f"Done. Added {added} new cards, skipped {skipped} duplicates.")
    print("\n--- Last 10 words in database ---")
    for kanji, reading, meaning in recent:
        print(f"  {kanji}（{reading}）= {meaning}")


if __name__ == "__main__":
    main()
