"""Run once: python jlpt_seed.py — seeds the jlpt_cards table with N4/N5 vocabulary."""
import sqlite3, os

DB_PATH = os.path.join(os.path.dirname(__file__), "kanji.db")

JLPT_WORDS = [
    # Numbers
    ("一", "いち", "one"),
    ("一つ", "ひとつ", "one thing"),
    ("一日", "いちにち", "one day"),
    ("一日", "ついたち", "first day of month"),
    ("二人", "ふたり", "two people"),
    ("二つ", "ふたつ", "two things"),
    ("二日", "ふつか", "second day / two days"),
    ("三つ", "みっつ", "three things"),
    ("三日", "みっか", "third day / three days"),
    ("四つ", "よっつ", "four things"),
    ("四日", "よっか", "fourth day / four days"),
    ("五つ", "いつつ", "five things"),
    ("五日", "いつか", "fifth day / five days"),
    ("六つ", "むっつ", "six things"),
    ("六日", "むいか", "sixth day / six days"),
    ("七つ", "ななつ", "seven things"),
    ("七日", "なのか", "seventh day / seven days"),
    ("八つ", "やっつ", "eight things"),
    ("八日", "ようか", "eighth day / eight days"),
    ("九つ", "ここのつ", "nine things"),
    ("九日", "ここのか", "ninth day / nine days"),
    ("十", "じゅう", "ten"),
    ("十", "とお", "ten (traditional reading)"),
    ("十日", "とおか", "tenth day / ten days"),
    ("二十", "にじゅう", "twenty"),
    ("二十日", "はつか", "twentieth day / twenty days"),
    ("三十", "さんじゅう", "thirty"),
    ("四十", "よんじゅう", "forty"),
    ("五十", "ごじゅう", "fifty"),
    ("六十", "ろくじゅう", "sixty"),
    ("七十", "ななじゅう", "seventy"),
    ("八十", "はちじゅう", "eighty"),
    ("九十", "きゅうじゅう", "ninety"),
    ("百", "ひゃく", "hundred"),
    ("二百", "にひゃく", "two hundred"),
    ("三百", "さんびゃく", "three hundred"),
    ("四百", "よんひゃく", "four hundred"),
    ("五百", "ごひゃく", "five hundred"),
    ("六百", "ろっぴゃく", "six hundred"),
    ("七百", "ななひゃく", "seven hundred"),
    ("八百", "はっぴゃく", "eight hundred"),
    ("九百", "きゅうひゃく", "nine hundred"),
    ("千", "せん", "thousand"),
    ("二千", "にせん", "two thousand"),
    ("三千", "さんぜん", "three thousand"),
    ("四千", "よんせん", "four thousand"),
    ("五千", "ごせん", "five thousand"),
    ("六千", "ろくせん", "six thousand"),
    ("七千", "ななせん", "seven thousand"),
    ("八千", "はっせん", "eight thousand"),
    ("九千", "きゅうせん", "nine thousand"),
    ("一万", "いちまん", "ten thousand"),
    ("二万", "にまん", "twenty thousand"),
    ("十万", "じゅうまん", "one hundred thousand"),
    ("百万", "ひゃくまん", "one million"),
    ("千万", "せんまん", "ten million"),
    ("一億", "いちおく", "one hundred million"),
    # Currency
    ("円", "えん", "yen"),
    ("お金", "おかね", "money"),
    ("お金持ち", "おかねもち", "rich person"),
    ("日本円", "にほんえん", "Japanese yen"),
    ("外円", "がいえん", "foreign currency"),
    ("円高", "えんだか", "strong yen"),
    ("円安", "えんやす", "weak yen"),
    ("百円玉", "ひゃくえんだま", "100 yen coin"),
    ("五百円玉", "ごひゃくえんだま", "500 yen coin"),
    # 日
    ("日", "ひ", "day / sun"),
    ("日本", "にほん", "Japan"),
    ("日本人", "にほんじん", "Japanese person"),
    ("日本語", "にほんご", "Japanese language"),
    ("今日", "きょう", "today"),
    ("昨日", "きのう", "yesterday"),
    ("明日", "あした", "tomorrow"),
    ("明後日", "あさって", "day after tomorrow"),
    ("一昨日", "おととい", "day before yesterday"),
    ("毎日", "まいにち", "every day"),
    ("日曜日", "にちようび", "Sunday"),
    ("日光", "にっこう", "sunlight"),
    ("日記", "にっき", "diary"),
    ("日出", "にっしゅつ", "sunrise"),
    ("日没", "にちぼつ", "sunset"),
    # 月
    ("月", "つき", "moon"),
    ("月", "がつ", "month (counter for months)"),
    ("一月", "いちがつ", "January"),
    ("二月", "にがつ", "February"),
    ("三月", "さんがつ", "March"),
    ("四月", "しがつ", "April"),
    ("五月", "ごがつ", "May"),
    ("六月", "ろくがつ", "June"),
    ("七月", "しちがつ", "July"),
    ("八月", "はちがつ", "August"),
    ("九月", "くがつ", "September"),
    ("十月", "じゅうがつ", "October"),
    ("十一月", "じゅういちがつ", "November"),
    ("十二月", "じゅうにがつ", "December"),
    ("月曜日", "げつようび", "Monday"),
    ("月光", "げっこう", "moonlight"),
    ("月見", "つきみ", "moon viewing"),
    ("満月", "まんげつ", "full moon"),
    ("新月", "しんげつ", "new moon"),
    # 火
    ("火", "ひ", "fire"),
    ("火曜日", "かようび", "Tuesday"),
    ("火事", "かじ", "fire (incident)"),
    ("火災", "かさい", "fire disaster"),
    ("花火", "はなび", "fireworks"),
    ("火山", "かざん", "volcano"),
    ("火口", "かこう", "crater"),
    ("火傷", "やけど", "burn"),
    ("火力", "かりょく", "firepower / heat"),
    # 水
    ("水", "みず", "water"),
    ("水曜日", "すいようび", "Wednesday"),
    ("水泳", "すいえい", "swimming"),
    ("水族館", "すいぞくかん", "aquarium"),
    ("水道", "すいどう", "water supply / tap water"),
    ("水着", "みずぎ", "swimsuit"),
    ("水色", "みずいろ", "light blue"),
    ("雨水", "あまみず", "rainwater"),
    ("水不足", "みずぶそく", "water shortage"),
    # 木
    ("木", "き", "tree"),
    ("木曜日", "もくようび", "Thursday"),
    ("木陰", "こかげ", "shade of a tree"),
    ("木々", "きぎ", "trees"),
    ("木材", "もくざい", "lumber"),
    ("木工", "もっこう", "woodworking"),
    ("木造", "もくぞう", "wooden construction"),
    # 金
    ("金", "きん", "gold"),
    ("金", "かね", "money"),
    ("金曜日", "きんようび", "Friday"),
    ("金持ち", "かねもち", "rich person"),
    ("金庫", "きんこ", "safe (for valuables)"),
    ("金属", "きんぞく", "metal"),
    ("金物", "かなもの", "hardware"),
    # 土
    ("土", "つち", "earth / soil"),
    ("土曜日", "どようび", "Saturday"),
    ("土砂", "どしゃ", "earth and sand"),
    ("土産", "みやげ", "souvenir"),
    ("土地", "とち", "land"),
    ("土木", "どぼく", "civil engineering"),
    ("土日", "どにち", "Saturday and Sunday"),
    # 山
    ("山", "やま", "mountain"),
    ("山田", "やまだ", "Yamada (common surname)"),
    ("山登り", "やまのぼり", "mountain climbing"),
    ("山脈", "さんみゃく", "mountain range"),
    ("山頂", "さんちょう", "mountain peak"),
    ("山里", "やまざと", "mountain village"),
    # 川
    ("川", "かわ", "river"),
    ("川口", "かわぐち", "river mouth"),
    ("川原", "かわら", "riverbank"),
    ("川辺", "かわべ", "riverside"),
    ("大川", "おおかわ", "large river"),
    ("小川", "おがわ", "stream / small river"),
    # 田
    ("田", "た", "rice field"),
    ("田んぼ", "たんぼ", "rice paddy"),
    ("田舎", "いなか", "countryside"),
    ("田園", "でんえん", "rural landscape"),
    ("田畑", "たはた", "fields and rice fields"),
    ("水田", "すいでん", "wet rice field"),
    # 人
    ("人", "ひと", "person"),
    ("人々", "ひとびと", "people"),
    ("人気", "にんき", "popularity"),
    ("人口", "じんこう", "population"),
    ("大人", "おとな", "adult"),
    ("外国人", "がいこくじん", "foreigner"),
    ("人間", "にんげん", "human being"),
    ("人物", "じんぶつ", "person / character"),
    ("一人", "ひとり", "one person"),
    # 口
    ("口", "くち", "mouth"),
    ("入口", "いりぐち", "entrance"),
    ("出口", "でぐち", "exit"),
    ("窓口", "まどぐち", "counter / service window"),
    ("口元", "くちもと", "around the mouth"),
    ("口調", "くちょう", "tone of voice"),
    ("口笛", "くちぶえ", "whistle"),
    # 手
    ("手", "て", "hand"),
    ("手紙", "てがみ", "letter"),
    ("手洗い", "てあらい", "restroom / hand washing"),
    ("手伝い", "てつだい", "help / assistance"),
    ("手帳", "てちょう", "notebook / planner"),
    ("手元", "てもと", "on hand / at hand"),
    ("手作り", "てづくり", "handmade"),
    ("手軽", "てがる", "easy / handy"),
    # 目
    ("目", "め", "eye"),
    ("目玉", "めだま", "eyeball"),
    ("目的", "もくてき", "purpose"),
    ("人目", "ひとめ", "public eye / attention"),
    ("目立つ", "めだつ", "to stand out"),
    ("目標", "もくひょう", "goal / target"),
    ("目上", "めうえ", "superior (person)"),
    ("目下", "めした", "inferior (person)"),
    # 耳
    ("耳", "みみ", "ear"),
    ("耳鼻科", "じびか", "ENT doctor"),
    ("耳元", "みみもと", "near the ear"),
    ("耳鳴り", "みみなり", "ringing in ears"),
    ("耳栓", "みみせん", "earplug"),
    # 足
    ("足", "あし", "foot / leg"),
    ("足元", "あしもと", "feet / underfoot"),
    ("足音", "あしおと", "footsteps"),
    ("足跡", "あしあと", "footprint"),
    ("足首", "あしくび", "ankle"),
    ("足指", "あしゆび", "toe"),
    # 力
    ("力", "ちから", "power / strength"),
    ("力持ち", "ちからもち", "strong person"),
    ("電力", "でんりょく", "electric power"),
    ("体力", "たいりょく", "physical strength / stamina"),
    ("能力", "のうりょく", "ability"),
    ("努力", "どりょく", "effort"),
    # 女
    ("女性", "じょせい", "woman / female"),
    ("女の子", "おんなのこ", "girl"),
    ("彼女", "かのじょ", "she / girlfriend"),
    ("女優", "じょゆう", "actress"),
    ("女性誌", "じょせいし", "women's magazine"),
    # 男
    ("男", "おとこ", "man / male"),
    ("男の子", "おとこのこ", "boy"),
    ("男女", "だんじょ", "men and women"),
    ("男性誌", "だんせいし", "men's magazine"),
    # 子
    ("子", "こ", "child"),
    ("子供", "こども", "child"),
    ("子犬", "こいぬ", "puppy"),
    ("子猫", "こねこ", "kitten"),
    ("子育て", "こそだて", "child rearing"),
    ("子ども達", "こどもたち", "children"),
    # 学
    ("学", "がく", "study / learning"),
    ("学校", "がっこう", "school"),
    ("学生", "がくせい", "student"),
    ("学びます", "まなびます", "to study / to learn"),
    ("学習", "がくしゅう", "study / learning"),
    ("学園", "がくえん", "academy"),
    ("学科", "がっか", "subject / course"),
    # 校
    ("高校", "こうこう", "high school"),
    ("校長", "こうちょう", "principal"),
    ("校則", "こうそく", "school rules"),
    ("校庭", "こうてい", "schoolyard"),
    ("校友", "こうゆう", "alumnus"),
    # 先
    ("先", "さき", "ahead / previous"),
    ("先生", "せんせい", "teacher"),
    ("先週", "せんしゅう", "last week"),
    ("先月", "せんげつ", "last month"),
    ("先日", "せんじつ", "the other day"),
    ("先に", "さきに", "ahead / beforehand"),
    # 生
    ("生", "せい", "life"),
    ("生", "なま", "raw / fresh"),
    ("生きます", "いきます", "to live"),
    ("生まれます", "うまれます", "to be born"),
    ("生活", "せいかつ", "life / living"),
    ("生徒", "せいと", "student (school)"),
    ("生命", "せいめい", "life"),
    ("生まれ", "うまれ", "birth / origin"),
    # 年
    ("年", "とし", "year"),
    ("今年", "ことし", "this year"),
    ("去年", "きょねん", "last year"),
    ("来年", "らいねん", "next year"),
    ("毎年", "まいとし", "every year"),
    ("年齢", "ねんれい", "age"),
    ("一年生", "いちねんせい", "first-year student"),
    # 本
    ("本", "ほん", "book / origin"),
    ("本屋", "ほんや", "bookstore"),
    ("本当", "ほんとう", "truth / real"),
    ("基本", "きほん", "foundation / basics"),
    ("本物", "ほんもの", "genuine article"),
    # 休
    ("休み", "やすみ", "rest / holiday"),
    ("休日", "きゅうじつ", "holiday"),
    ("休みます", "やすみます", "to rest"),
    ("休憩", "きゅうけい", "break"),
    # 見
    ("見ます", "みます", "to see"),
    ("見物", "けんぶつ", "sightseeing"),
    ("見学", "けんがく", "observation / study visit"),
    ("見方", "みかた", "viewpoint"),
    ("見えます", "みえます", "to be visible"),
    # 行
    ("行きます", "いきます", "to go"),
    ("旅行", "りょこう", "travel"),
    ("銀行", "ぎんこう", "bank"),
    ("行います", "おこないます", "to do / perform"),
    ("行き", "いき", "going / bound for"),
    # 来
    ("来ます", "きます", "to come"),
    ("未来", "みらい", "future"),
    ("来場", "らいじょう", "attendance"),
    # 食
    ("食べます", "たべます", "to eat"),
    ("食事", "しょくじ", "meal"),
    ("食べ物", "たべもの", "food"),
    ("食堂", "しょくどう", "dining hall"),
    # 飲
    ("飲みます", "のみます", "to drink"),
    ("飲み物", "のみもの", "beverage"),
    ("飲酒", "いんしゅ", "drinking alcohol"),
    # 書
    ("書きます", "かきます", "to write"),
    ("辞書", "じしょ", "dictionary"),
    ("書類", "しょるい", "documents"),
    # 読
    ("読みます", "よみます", "to read"),
    ("読書", "どくしょ", "reading (hobby)"),
    ("読み方", "よみかた", "how to read / reading"),
    # 話
    ("話します", "はなします", "to speak"),
    ("電話", "でんわ", "telephone"),
    ("会話", "かいわ", "conversation"),
    ("話し合います", "はなしあいます", "to discuss"),
    # 聞
    ("聞きます", "ききます", "to hear / to ask"),
    ("新聞", "しんぶん", "newspaper"),
    ("聞こえます", "きこえます", "to be audible"),
    # 入
    ("入ります", "はいります", "to enter"),
    ("入浴", "にゅうよく", "bath"),
    ("入学", "にゅうがく", "school entrance"),
    # 出
    ("出ます", "でます", "to exit / to appear"),
    ("出身", "しゅっしん", "hometown / origin"),
    ("外出", "がいしゅつ", "going out"),
    # 上・下・中・外
    ("上", "うえ", "up / above"),
    ("上ります", "のぼります", "to go up"),
    ("上手", "じょうず", "skilled"),
    ("上着", "うわぎ", "jacket / top clothing"),
    ("上がります", "あがります", "to go up / rise"),
    ("下", "した", "down / below"),
    ("下りります", "おります", "to get off / to descend"),
    ("下手", "へた", "unskilled"),
    ("下着", "したぎ", "underwear"),
    ("下がります", "さがります", "to go down / fall"),
    ("中", "なか", "inside / middle"),
    ("中に", "なかに", "inside"),
    ("日本中", "にほんじゅう", "all over Japan"),
    ("中学生", "ちゅうがくせい", "junior high school student"),
    ("中古", "ちゅうこ", "used (item)"),
    ("外", "そと", "outside"),
    ("外食", "がいしょく", "eating out"),
    ("外側", "そとがわ", "outer side"),
    # 左・右
    ("左", "ひだり", "left"),
    ("左折", "させつ", "left turn"),
    ("左手", "ひだりて", "left hand"),
    ("左側", "ひだりがわ", "left side"),
    ("右", "みぎ", "right"),
    ("右折", "うせつ", "right turn"),
    ("右手", "みぎて", "right hand"),
    ("右側", "みぎがわ", "right side"),
    # Size
    ("大きい", "おおきい", "big"),
    ("大好き", "だいすき", "love / like very much"),
    ("大事", "だいじ", "important"),
    ("大学", "だいがく", "university"),
    ("小さい", "ちいさい", "small"),
    ("小学校", "しょうがっこう", "elementary school"),
    ("小説", "しょうせつ", "novel"),
    ("多い", "おおい", "many"),
    ("多分", "たぶん", "probably"),
    ("多数", "たすう", "majority"),
    ("多国籍", "たこくせき", "multinational"),
    ("少ない", "すくない", "few"),
    ("少し", "すこし", "a little"),
    ("少女", "しょうじょ", "young girl"),
    ("少年", "しょうねん", "young boy"),
    # New / Old / Colors
    ("新しい", "あたらしい", "new"),
    ("新入生", "しんにゅうせい", "new student"),
    ("新宿", "しんじゅく", "Shinjuku (place name)"),
    ("古い", "ふるい", "old"),
    ("古本", "ふるほん", "used book"),
    ("古着", "ふるぎ", "used clothing"),
    ("白い", "しろい", "white"),
    ("白黒", "しろくろ", "black and white"),
    ("白髪", "しらが", "white hair"),
    ("黒い", "くろい", "black"),
    ("黒板", "こくばん", "blackboard"),
    ("黒髪", "くろかみ", "black hair"),
    ("赤い", "あかい", "red"),
    ("赤ちゃん", "あかちゃん", "baby"),
    ("赤信号", "あかしんごう", "red light"),
    ("青い", "あおい", "blue"),
    ("青信号", "あおしんごう", "green light"),
    ("青空", "あおぞら", "blue sky"),
    # Adjectives
    ("早い", "はやい", "early"),
    ("早速", "さっそく", "immediately"),
    ("早朝", "そうちょう", "early morning"),
    ("長い", "ながい", "long"),
    ("長所", "ちょうしょ", "strong point"),
    ("長男", "ちょうなん", "eldest son"),
    ("安い", "やすい", "cheap"),
    ("安心", "あんしん", "relief"),
    ("安全", "あんぜん", "safety"),
    ("高い", "たかい", "high / expensive"),
    ("高齢", "こうれい", "old age"),
    ("好き", "すき", "like"),
    ("大好き", "だいすき", "love / like very much"),
    ("好みます", "このみます", "to prefer"),
    # Time expressions
    ("毎週", "まいしゅう", "every week"),
    ("毎月", "まいつき", "every month"),
    ("今", "いま", "now"),
    ("今朝", "けさ", "this morning"),
    ("今週", "こんしゅう", "this week"),
    ("今夜", "こんや", "tonight"),
    ("時間", "じかん", "time / hour"),
    ("時々", "ときどき", "sometimes"),
    ("時代", "じだい", "era"),
    ("間", "あいだ", "interval / between"),
    ("間に合います", "まにあいます", "to be in time"),
    ("前", "まえ", "front / before"),
    ("前日", "ぜんじつ", "previous day"),
    ("名前", "なまえ", "name"),
    ("前もって", "まえもって", "in advance"),
    ("後", "あと", "behind / after"),
    ("後で", "あとで", "later"),
    ("午後", "ごご", "afternoon"),
    ("後ろ", "うしろ", "behind"),
    # Directions
    ("北", "きた", "north"),
    ("北海道", "ほっかいどう", "Hokkaido"),
    ("北口", "きたぐち", "north exit"),
    ("北風", "きたかぜ", "north wind"),
    ("南", "みなみ", "south"),
    ("南口", "みなみぐち", "south exit"),
    ("南米", "なんべい", "South America"),
    ("南風", "みなみかぜ", "south wind"),
    ("東", "ひがし", "east"),
    ("東京", "とうきょう", "Tokyo"),
    ("東口", "ひがしぐち", "east exit"),
    ("東南", "とうなん", "southeast"),
    ("西", "にし", "west"),
    ("西口", "にしぐち", "west exit"),
    ("関西", "かんさい", "Kansai region"),
    ("西南", "せいなん", "southwest"),
    # Question words
    ("何", "なに", "what"),
    ("何時", "なんじ", "what time"),
    ("何で", "なんで", "why"),
    ("何か", "なにか", "something"),
    ("誰", "だれ", "who"),
    ("誰か", "だれか", "someone"),
    ("誰でも", "だれでも", "anyone"),
    # 名・国・語
    ("有名", "ゆうめい", "famous"),
    ("国籍", "こくせき", "nationality"),
    ("国語", "こくご", "Japanese language (school subject)"),
    ("外国", "がいこく", "foreign country"),
    ("国際", "こくさい", "international"),
    ("英語", "えいご", "English language"),
    # Transport
    ("車", "くるま", "car"),
    ("電車", "でんしゃ", "train"),
    ("自動車", "じどうしゃ", "automobile"),
    ("車道", "しゃどう", "road (for cars)"),
    ("電気", "でんき", "electricity"),
    ("駅", "えき", "station"),
    ("駅前", "えきまえ", "in front of station"),
    ("駅員", "えきいん", "station staff"),
    ("駅ビル", "えきびる", "station building"),
    # Company / Shop
    ("会社", "かいしゃ", "company"),
    ("社長", "しゃちょう", "company president"),
    ("神社", "じんじゃ", "Shinto shrine"),
    ("店", "みせ", "shop"),
    ("店員", "てんいん", "shop clerk"),
    ("店長", "てんちょう", "shop manager"),
    ("本店", "ほんてん", "main store"),
    # N4 — Meeting / Same / Work
    ("会います", "あいます", "to meet"),
    ("会議", "かいぎ", "meeting"),
    ("会場", "かいじょう", "venue"),
    ("大会", "たいかい", "tournament / convention"),
    ("同じ", "おなじ", "same"),
    ("同時", "どうじ", "simultaneous"),
    ("同居", "どうきょ", "living together"),
    ("同一", "どういつ", "identical"),
    ("仕事", "しごと", "work / job"),
    ("用事", "ようじ", "errand / business"),
    # Using / Making
    ("使います", "つかいます", "to use"),
    ("使い方", "つかいかた", "how to use"),
    ("使用", "しよう", "use"),
    ("使者", "ししゃ", "messenger"),
    ("作ります", "つくります", "to make"),
    ("作品", "さくひん", "work / creation"),
    ("作文", "さくぶん", "composition"),
    ("動作", "どうさ", "movement / action"),
    ("操作", "そうさ", "operation"),
    # Understanding / Knowing
    ("分かります", "わかります", "to understand"),
    ("半分", "はんぶん", "half"),
    ("一分", "いっぷん", "one minute"),
    ("十分", "じゅっぷん", "ten minutes / enough"),
    ("分けます", "わけます", "to divide"),
    ("思います", "おもいます", "to think"),
    ("思想", "しそう", "thought / ideology"),
    ("思い出", "おもいで", "memory / recollection"),
    ("思案", "しあん", "deliberation"),
    ("知ります", "しります", "to know / to learn"),
    ("知らせます", "しらせます", "to inform"),
    ("知識", "ちしき", "knowledge"),
    ("知人", "ちじん", "acquaintance"),
    ("知恵", "ちえ", "wisdom"),
    # Possessing / Living / Working
    ("持ちます", "もちます", "to hold / to have"),
    ("持参", "じさん", "bringing (one's own)"),
    ("所持", "しょじ", "possession"),
    ("維持", "いじ", "maintenance"),
    ("住所", "じゅうしょ", "address"),
    ("居住", "きょじゅう", "residence"),
    ("住人", "じゅうにん", "resident"),
    ("働きます", "はたらきます", "to work"),
    ("労働", "ろうどう", "labor"),
    ("働き手", "はたらきて", "worker"),
    # Teaching / Thinking
    ("教えます", "おしえます", "to teach"),
    ("教育", "きょういく", "education"),
    ("宗教", "しゅうきょう", "religion"),
    ("考えます", "かんがえます", "to think"),
    ("参考", "さんこう", "reference"),
    ("考え", "かんがえ", "thought / idea"),
    ("検討", "けんとう", "consideration"),
    # Sending / Waiting
    ("送信", "そうしん", "transmission / sending"),
    ("配達", "はいたつ", "delivery"),
    ("送別", "そうべつ", "farewell"),
    ("待ちます", "まちます", "to wait"),
    ("待ち合わせ", "まちあわせ", "meeting up"),
    ("期待", "きたい", "expectation"),
    ("待機", "たいき", "standby"),
    # Wearing / Returning
    ("着ます", "きます", "to wear"),
    ("服装", "ふくそう", "clothing / attire"),
    ("到着", "とうちゃく", "arrival"),
    ("着手", "ちゃくしゅ", "starting / beginning"),
    ("帰ります", "かえります", "to return home"),
    ("帰国", "きこく", "returning to one's country"),
    ("帰宅", "きたく", "returning home"),
    ("帰省", "きせい", "home visit"),
    # Starting / Ending
    ("開始", "かいし", "start"),
    ("始発", "しはつ", "first departure (train/bus)"),
    ("終わります", "おわります", "to end"),
    ("終了", "しゅうりょう", "finish"),
    ("終点", "しゅうてん", "terminus"),
    ("終業", "しゅうぎょう", "end of work"),
    ("連続", "れんぞく", "series / continuous"),
    ("続き", "つづき", "continuation"),
    ("継続", "けいぞく", "continuation"),
    # Buying / Selling
    ("売ります", "うります", "to sell"),
    ("売り場", "うりば", "sales floor"),
    ("販売", "はんばい", "sales"),
    ("売買", "ばいばい", "buying and selling"),
    ("買います", "かいます", "to buy"),
    ("買い物", "かいもの", "shopping"),
    ("購入", "こうにゅう", "purchase"),
    ("買収", "ばいしゅう", "acquisition / bribery"),
    # Taking / Receiving
    ("取ります", "とります", "to take"),
    ("取扱い", "とりあつかい", "handling"),
    ("取得", "しゅとく", "acquisition"),
    ("写真", "しゃしん", "photo"),
    ("取引", "とりひき", "transaction"),
    ("受けます", "うけます", "to receive"),
    ("受付", "うけつけ", "reception desk"),
    ("受信", "じゅしん", "reception (signal)"),
    ("受講", "じゅこう", "taking a course"),
    # Answering / Carrying
    ("答え", "こたえ", "answer"),
    ("回答", "かいとう", "reply"),
    ("解答", "かいとう", "solution / correct answer"),
    ("運びます", "はこびます", "to carry"),
    ("運命", "うんめい", "fate"),
    ("運転", "うんてん", "driving"),
    ("運動", "うんどう", "exercise"),
    # Moving / Deciding
    ("動きます", "うごきます", "to move"),
    ("動物", "どうぶつ", "animal"),
    ("動機", "どうき", "motive"),
    ("決めます", "きめます", "to decide"),
    ("決定", "けってい", "decision"),
    ("決心", "けっしん", "determination"),
    # Recording / Explaining
    ("記録", "きろく", "record"),
    ("記憶", "きおく", "memory"),
    ("記念", "きねん", "commemoration"),
    ("記入", "きにゅう", "entry (form filling)"),
    ("説明", "せつめい", "explanation"),
    ("説得", "せっとく", "persuasion"),
    ("解説", "かいせつ", "commentary"),
    # Testing / Experiencing
    ("試します", "ためします", "to try"),
    ("試験", "しけん", "exam"),
    ("試合", "しあい", "match / game"),
    ("試着", "しちゃく", "trying on clothes"),
    ("経験", "けいけん", "experience"),
    ("体験", "たいけん", "personal experience"),
    # Copying / Truth / Movies
    ("写します", "うつします", "to copy"),
    ("写生", "しゃせい", "sketching from life"),
    ("真実", "しんじつ", "truth"),
    ("真面目", "まじめ", "serious / earnest"),
    ("真似", "まね", "imitation"),
    ("映ります", "うつります", "to be reflected"),
    ("映画", "えいが", "movie"),
    ("反映", "はんえい", "reflection"),
    ("画面", "がめん", "screen"),
    ("絵画", "かいが", "painting"),
    # Music / Sound
    ("曲", "きょく", "music / tune"),
    ("曲がります", "まがります", "to turn / to bend"),
    ("作曲", "さっきょく", "musical composition"),
    ("歌", "うた", "song"),
    ("歌います", "うたいます", "to sing"),
    ("歌手", "かしゅ", "singer"),
    ("歌声", "うたごえ", "singing voice"),
    ("音", "おと", "sound"),
    ("音楽", "おんがく", "music"),
    ("音声", "おんせい", "voice / audio"),
    ("発音", "はつおん", "pronunciation"),
    ("楽しい", "たのしい", "fun"),
    ("楽器", "がっき", "musical instrument"),
    # Health / Medicine
    ("病気", "びょうき", "sickness"),
    ("病院", "びょういん", "hospital"),
    ("病人", "びょうにん", "sick person"),
    ("医院", "いいん", "clinic"),
    ("薬", "くすり", "medicine"),
    ("薬局", "やっきょく", "pharmacy"),
    ("薬剤師", "やくざいし", "pharmacist"),
    ("飲み薬", "のみぐすり", "oral medicine"),
    # Body
    ("体", "からだ", "body"),
    ("体調", "たいちょう", "physical condition"),
    ("体重", "たいじゅう", "body weight"),
    ("頭", "あたま", "head"),
    ("頭痛", "ずつう", "headache"),
    ("頭脳", "ずのう", "brain / intelligence"),
    ("頭文字", "かしらもじ", "first letter / initial"),
    ("顔色", "かおいろ", "complexion"),
    ("顔見知り", "かおみしり", "acquaintance"),
    ("顔立ち", "かおだち", "facial features"),
    ("心", "こころ", "heart / mind"),
    ("心配", "しんぱい", "worry"),
    ("心臓", "しんぞう", "heart (organ)"),
    ("心から", "こころから", "from the bottom of the heart"),
    # Feeling / Weather
    ("元気", "げんき", "healthy / energetic"),
    ("天気", "てんき", "weather"),
    ("気持ち", "きもち", "feeling"),
    ("気分", "きぶん", "mood"),
    ("天才", "てんさい", "genius"),
    ("天井", "てんじょう", "ceiling"),
    ("空気", "くうき", "air"),
    ("空港", "くうこう", "airport"),
    # Nature / Water
    ("海辺", "うみべ", "seaside"),
    ("海外", "かいがい", "overseas"),
    ("海水", "かいすい", "seawater"),
    ("池", "いけ", "pond"),
    ("庭池", "にわいけ", "garden pond"),
    ("湖", "みずうみ", "lake"),
    ("湖水", "こすい", "lake water"),
    ("島", "しま", "island"),
    ("半島", "はんとう", "peninsula"),
    ("林", "はやし", "woods"),
    ("林業", "りんぎょう", "forestry"),
    ("森", "もり", "forest"),
    ("森林", "しんりん", "forest"),
    ("岩", "いわ", "rock"),
    ("岩山", "いわやま", "rocky mountain"),
    ("石ころ", "いしころ", "pebble"),
    # Plants / Animals
    ("花", "はな", "flower"),
    ("花見", "はなみ", "cherry blossom viewing"),
    ("花瓶", "かびん", "vase"),
    ("草むら", "くさむら", "grass patch"),
    ("鳥", "とり", "bird"),
    ("鳥肌", "とりはだ", "goosebumps"),
    ("焼き鳥", "やきとり", "grilled chicken skewer"),
    ("小鳥", "ことり", "small bird"),
    ("魚", "さかな", "fish"),
    ("魚屋", "さかなや", "fish shop"),
    ("焼き魚", "やきざかな", "grilled fish"),
    ("魚介類", "ぎょかいるい", "seafood"),
    ("犬", "いぬ", "dog"),
    ("犬小屋", "いぬごや", "doghouse"),
    ("野良犬", "のらいぬ", "stray dog"),
    ("猫", "ねこ", "cat"),
    ("猫好き", "ねこずき", "cat lover"),
    ("野良猫", "のらねこ", "stray cat"),
    ("牛", "うし", "cow"),
    ("牛肉", "ぎゅうにく", "beef"),
    ("牛乳", "ぎゅうにゅう", "milk"),
    ("牛小屋", "うしごや", "cowshed"),
    ("馬", "うま", "horse"),
    ("馬肉", "ばにく", "horse meat"),
    ("馬力", "ばりき", "horsepower"),
    ("豚肉", "ぶたにく", "pork"),
    ("鳥肉", "とりにく", "chicken meat"),
    # Food / Drink
    ("お茶", "おちゃ", "tea"),
    ("茶色", "ちゃいろ", "brown"),
    ("紅茶", "こうちゃ", "black tea"),
    ("米", "こめ", "rice (uncooked)"),
    ("米国", "べいこく", "America (USA)"),
    ("ご飯", "ごはん", "cooked rice / meal"),
    ("米粒", "こめつぶ", "grain of rice"),
    ("野原", "のはら", "field"),
    ("野菜", "やさい", "vegetable"),
    ("野鳥", "やちょう", "wild bird"),
    ("菜園", "さいえん", "vegetable garden"),
    ("果物", "くだもの", "fruit"),
    ("効果", "こうか", "effect"),
    ("結果", "けっか", "result"),
    ("油", "あぶら", "oil"),
    ("油断", "ゆだん", "carelessness"),
    # Cooking / Industry
    ("料理", "りょうり", "cooking / dish"),
    ("料理します", "りょうりします", "to cook"),
    ("日本料理", "にほんりょうり", "Japanese cuisine"),
    ("料金", "りょうきん", "fee"),
    ("材料", "ざいりょう", "ingredients"),
    ("授業料", "じゅぎょうりょう", "tuition"),
    ("理由", "りゆう", "reason"),
    ("理学", "りがく", "science"),
    ("工業", "こうぎょう", "industry"),
    ("産業", "さんぎょう", "industry"),
    ("農業", "のうぎょう", "agriculture"),
    ("商業", "しょうぎょう", "commerce"),
    ("生産", "せいさん", "production"),
    ("産地", "さんち", "producing area"),
    ("商品", "しょうひん", "product"),
    ("品質", "ひんしつ", "quality"),
    # Luggage / Bank / Rail
    ("貨物", "かもつ", "cargo"),
    ("銀色", "ぎんいろ", "silver color"),
    ("鉄道", "てつどう", "railway"),
    ("鉄鋼", "てっこう", "steel"),
    ("化学", "かがく", "chemistry"),
    ("化けます", "ばけます", "to transform"),
    ("道具", "どうぐ", "tool"),
    ("代金", "だいきん", "payment / price"),
    ("代わり", "かわり", "substitute"),
    ("方式", "ほうしき", "method / system"),
    ("式場", "しきじょう", "ceremony hall"),
    ("方法", "ほうほう", "method"),
    ("法律", "ほうりつ", "law"),
    # World / All / Part
    ("世界", "せかい", "world"),
    ("学界", "がっかい", "academic world"),
    ("全く", "まったく", "completely"),
    ("全部", "ぜんぶ", "all"),
    ("半日", "はんにち", "half day"),
    ("半ば", "なかば", "middle / halfway"),
    ("部分", "ぶぶん", "part"),
    ("部屋", "へや", "room"),
    # Staff / Roles / Places
    ("係員", "かかりいん", "clerk / staff in charge"),
    ("係わります", "かかわります", "to be involved"),
    ("社員", "しゃいん", "employee"),
    ("役割", "やくわり", "role"),
    ("役所", "やくしょ", "government office"),
    ("郵便局", "ゆうびんきょく", "post office"),
    ("警察局", "けいさつきょく", "police station"),
    ("場所", "ばしょ", "place"),
    ("事務所", "じむしょ", "office"),
    ("台所", "だいどころ", "kitchen"),
    ("場合", "ばあい", "case / situation"),
    ("試合場", "しあいじょう", "competition venue"),
    ("会議室", "かいぎしつ", "meeting room"),
    ("寝室", "しんしつ", "bedroom"),
    # Family / Home
    ("家賃", "やちん", "rent"),
    ("家族", "かぞく", "family"),
    ("家内", "かない", "wife (own)"),
    ("花屋", "はなや", "flower shop"),
    ("肉屋", "にくや", "butcher shop"),
    ("専門", "せんもん", "specialty"),
    ("門限", "もんげん", "curfew"),
    ("戸棚", "とだな", "cupboard"),
    ("戸口", "とぐち", "doorway"),
    ("殿堂", "でんどう", "hall of fame"),
    ("お寺", "おてら", "temple"),
    ("寺院", "じいん", "temple"),
    ("神様", "かみさま", "god / deity"),
    # Transport / Road
    ("通ります", "とおります", "to pass through"),
    ("通います", "かよいます", "to commute"),
    ("普通", "ふつう", "normal"),
    ("交通", "こうつう", "traffic"),
    ("道路", "どうろ", "road"),
    ("歩道", "ほどう", "sidewalk"),
    ("路線", "ろせん", "route"),
    ("近い", "ちかい", "near"),
    ("近所", "きんじょ", "neighborhood"),
    ("最近", "さいきん", "recently"),
    ("近く", "ちかく", "nearby / soon"),
    ("遠い", "とおい", "far"),
    ("遠く", "とおく", "far away"),
    ("遠足", "えんそく", "field trip"),
    ("速い", "はやい", "fast"),
    ("速度", "そくど", "speed"),
    ("速達", "そくたつ", "express delivery"),
    ("遅い", "おそい", "slow / late"),
    # Weight / Size
    ("重い", "おもい", "heavy"),
    ("重要", "じゅうよう", "important"),
    ("軽い", "かるい", "light (weight)"),
    ("軽音楽", "けいおんがく", "light music"),
    ("軽自動車", "けいじどうしゃ", "compact car"),
    ("低い", "ひくい", "low"),
    ("低音", "ていおん", "low sound"),
    ("低温", "ていおん", "low temperature"),
    ("広い", "ひろい", "wide"),
    ("広告", "こうこく", "advertisement"),
    ("広場", "ひろば", "plaza"),
    ("暗い", "くらい", "dark"),
    ("暗記", "あんき", "memorization"),
    ("暗闇", "くらやみ", "darkness"),
    ("明るい", "あかるい", "bright"),
    ("明らか", "あきらか", "obvious"),
    ("短い", "みじかい", "short"),
    ("短期", "たんき", "short term"),
    ("短所", "たんしょ", "weak point"),
    ("静寂", "せいじゃく", "silence"),
    ("忙しい", "いそがしい", "busy"),
    ("忙殺", "ぼうさつ", "being kept extremely busy"),
    ("簡単", "かんたん", "simple"),
    ("容易", "ようい", "easy"),
    ("難しい", "むずかしい", "difficult"),
    ("難問", "なんもん", "difficult problem"),
    ("悪者", "わるもの", "villain"),
    ("悪口", "わるぐち", "insult"),
    ("良心", "りょうしん", "conscience"),
    ("正しい", "ただしい", "correct"),
    ("正解", "せいかい", "right answer"),
    ("正直", "しょうじき", "honesty"),
    # Separate / Special
    ("別れます", "わかれます", "to separate"),
    ("特別", "とくべつ", "special"),
    ("別に", "べつに", "not particularly"),
    ("特急", "とっきゅう", "express train"),
    # Existence / Necessity
    ("あります", "あります", "to have / to exist"),
    ("有効", "ゆうこう", "effective / valid"),
    ("ありません", "ありません", "there is not"),
    ("無料", "むりょう", "free of charge"),
    ("無理", "むり", "impossible"),
    ("必ず", "かならず", "without fail"),
    ("必要", "ひつよう", "necessary"),
    ("必死", "ひっし", "desperate"),
    ("要ります", "いります", "to need"),
    ("要求", "ようきゅう", "request / demand"),
    # Questions / Research
    ("問います", "といます", "to ask"),
    ("問題", "もんだい", "problem"),
    ("質問", "しつもん", "question"),
    ("問い合わせ", "といあわせ", "inquiry"),
    ("題名", "だいめい", "title"),
    ("答えます", "こたえます", "to answer"),
    ("研究", "けんきゅう", "research"),
    ("研究室", "けんきゅうしつ", "laboratory"),
    ("研修", "けんしゅう", "training"),
    ("告げます", "つげます", "to tell"),
    ("調査", "ちょうさ", "survey"),
    ("調べます", "しらべます", "to investigate"),
    # Promises / Plans
    ("約束", "やくそく", "promise"),
    ("約", "やく", "approximately"),
    ("改めます", "あらためます", "to revise"),
    ("改善", "かいぜん", "improvement"),
    ("定めます", "さだめます", "to decide / to set"),
    ("一定", "いってい", "fixed / certain"),
    ("利きます", "ききます", "to be effective"),
    ("害", "がい", "harm"),
    ("被害", "ひがい", "damage"),
    # Happiness / Love / Peace
    ("福", "ふく", "fortune"),
    ("幸福", "こうふく", "happiness"),
    ("幸せ", "しあわせ", "happiness"),
    ("幸い", "さいわい", "fortunately"),
    ("愛します", "あいします", "to love"),
    ("愛人", "あいじん", "lover"),
    ("平ら", "たいら", "flat"),
    ("平和", "へいわ", "peace"),
    ("平等", "びょうどう", "equality"),
    ("和食", "わしょく", "Japanese food"),
    ("協会", "きょうかい", "association"),
    # Conflict
    ("争います", "あらそいます", "to argue / to compete"),
    ("戦争", "せんそう", "war"),
    ("勝負", "しょうぶ", "match"),
    ("負けます", "まけます", "to lose"),
    ("負担", "ふたん", "burden"),
    ("敗れます", "やぶれます", "to be defeated"),
    ("残り", "のこり", "remainder"),
    # Disappear / Decrease / Increase
    ("消します", "けします", "to erase / to turn off"),
    ("消えます", "きえます", "to disappear"),
    ("減ります", "へります", "to decrease"),
    ("減少", "げんしょう", "decrease"),
    ("増加", "ぞうか", "increase"),
    ("移ります", "うつります", "to move / to transfer"),
    # Pull / Push / Throw / Hit
    ("引きます", "ひきます", "to pull"),
    ("引越し", "ひっこし", "moving house"),
    ("押します", "おします", "to push"),
    ("押し入れ", "おしいれ", "closet"),
    ("投げます", "なげます", "to throw"),
    ("投資", "とうし", "investment"),
    ("打ちます", "うちます", "to hit"),
    ("打ち合わせ", "うちあわせ", "meeting / discussion"),
    # Pay / Reply / Call
    ("払います", "はらいます", "to pay"),
    ("支払い", "しはらい", "payment"),
    ("返事", "へんじ", "reply"),
    ("呼びます", "よびます", "to call"),
    ("呼び出します", "よびだします", "to summon"),
    # Stop / Race / Climb
    ("止まります", "とまります", "to stop"),
    ("止めます", "とめます", "to stop (transitive)"),
    ("競走", "きょうそう", "race"),
    ("登ります", "のぼります", "to climb"),
    ("登山", "とざん", "mountain climbing"),
    ("降ります", "おります", "to get off"),
    ("降水", "こうすい", "precipitation"),
    ("乗ります", "のります", "to ride"),
    # Open / Close
    ("開けます", "あけます", "to open (transitive)"),
    ("閉じます", "とじます", "to close"),
    ("閉めます", "しめます", "to close (transitive)"),
]


def main():
    if not os.path.exists(DB_PATH):
        print(f"Database not found at {DB_PATH}. Start app.py first to create it.")
        return

    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS jlpt_cards (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            word TEXT NOT NULL,
            reading TEXT NOT NULL,
            meaning TEXT NOT NULL
        )
    """)

    existing = {(r[0], r[1]) for r in conn.execute("SELECT word, reading FROM jlpt_cards")}

    added = skipped = 0
    for word, reading, meaning in JLPT_WORDS:
        if (word, reading) in existing:
            skipped += 1
        else:
            conn.execute(
                "INSERT INTO jlpt_cards (word, reading, meaning) VALUES (?,?,?)",
                (word, reading, meaning),
            )
            existing.add((word, reading))
            added += 1

    conn.commit()
    conn.close()
    print(f"Done. Added {added} JLPT cards, skipped {skipped} duplicates.")


if __name__ == "__main__":
    main()
